### PR TITLE
Minor fixes pro first release cut

### LINKED ISSUE #10: Spec should refer to nvidiaContainerToolkit
The following 
https://github.com/NVIDIA/holodeck/blob/227eeed131fae2e9d4c70d319c9e0c1d274ad2e9/api/holodeck/v1alpha1/types.go#L37

should be `nvidiaContainerToolkit` and not `nvContainerToolKit`.

At the very least this should be `nvContainerToolkit`.

### LINKED ISSUE #11: Spec should refer to nvidiaDriver instead of nvDriver
In the following: https://github.com/NVIDIA/holodeck/blob/227eeed131fae2e9d4c70d319c9e0c1d274ad2e9/api/holodeck/v1alpha1/types.go#L37

`nvDriver` should be `nvidiaDriver`.

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Fixes #10 
Fixes #11

### CODE REVIEW

File: api/holodeck/v1alpha1/types.go [hunk 1]
```diff
@@ -189,7 +189,7 @@ type ExtraPortMapping struct {
 	HostPort      int `json:"hostPort"`
 }
 
-type NVContainerToolKit struct {
+type NVContainerToolkit struct {
```
Comment (elezar) [inline api/holodeck/v1alpha1/types.go:192]: Just to clarify. These types are actually private?

File: api/holodeck/v1alpha1/types.go [hunk 2]
```diff
@@ -30,11 +30,11 @@ type EnvironmentSpec struct {
 	Instance `json:"instance"`
 
 	// +optional
-	NVDriver NVDriver `json:"nvDriver"`
+	NVDriver NVDriver `json:"nvidiaDriver"`
 	// +optional
 	ContainerRuntime ContainerRuntime `json:"containerRuntime"`
 	// +optional
-	NVContainerToolKit NVContainerToolKit `json:"nvContainerToolKit"`
+	NVContainerToolkit NVContainerToolkit `json:"nvidiaContainerToolkit"`
```
Comment (elezar) [inline api/holodeck/v1alpha1/types.go:37]: Nit:
```suggestion
	NVIDIAContainerToolkit NVContainerToolkit `json:"nvidiaContainerToolkit"`
```

File: api/holodeck/v1alpha1/types.go [hunk 3]
```diff
@@ -30,11 +30,11 @@ type EnvironmentSpec struct {
 	Instance `json:"instance"`
 
 	// +optional
-	NVDriver NVDriver `json:"nvDriver"`
+	NVDriver NVDriver `json:"nvidiaDriver"`
```
Comment (elezar) [inline api/holodeck/v1alpha1/types.go:33]: Nit:
```suggestion
	NVIDIADriver NVDriver `json:"nvidiaDriver"`
```

File: Makefile [hunk 4]
```diff
@@ -40,16 +40,26 @@ verify:
 	    exit 1; \
 	fi
 
+release:
```
Comment (elezar) [inline Makefile:43]: Question: How does this compare to releasing other tools?

**Review by elezar — APPROVED** [review]
Minor comments, but they're not blockers.

File: Makefile (hunk 4 above)
Comment (ArangoGutierrez) [reply Makefile:43]: the idea for this project is to have the release binaries ready to be downloaded. all of our products are released via container images, but this one is meant to be used as a command line tool

File: api/holodeck/v1alpha1/types.go (hunk 1 above)
Comment (ArangoGutierrez) [reply api/holodeck/v1alpha1/types.go:192]: we could move this to `pkg/apis` as the controller-runtime recommends

Comment (ArangoGutierrez) [reply api/holodeck/v1alpha1/types.go:192]: if we make the api public, we could potentially use holodeck all from go code, without a config file , it will be possible to import the `v1alpha1` spec and then call the create/delete functions.
maybe a good TODO for `v0.1.1`

Comment (ArangoGutierrez) [reply api/holodeck/v1alpha1/types.go]: https://github.com/NVIDIA/holodeck/issues/15
